### ISSUE TITLE
자체 러스트코리아 로고 만들기

### ISSUE THREAD

**Issue by simnalamburt** [rust-kr/rust-kr-rust#25]
#### PNG preview
<p align=center><img src="https://cloud.githubusercontent.com/assets/4435445/12703804/289e7c14-c88f-11e5-8a1e-e876119799b1.png"></p>

> 이 이슈는 어도비 일러스트레이터 파일을 저장하기 위해 만들어졌습니다

일단 프로토타입이라고 생각하면서 적당히 만들어봤습니다. 어도비 일러스트레이터 파일도 같이 첨부하니, 더 손보고싶으신분은 고쳐주세요.

- :floppy_disk: [rust-korea.ai.zip](https://github.com/rust-kr/rust-kr-rust/files/111413/rust-korea.zip)
- :floppy_disk: [rust-korea.svg.zip](https://github.com/rust-kr/rust-kr-rust/files/111438/rust-korea.svg.zip)

#### 이 로고가 들어갈곳
- [x] http://rust-kr.org/
- [x] https://github.com/rust-kr

> Distributed under CC-BY

**Comment by simnalamburt** [comment]
## TODO
- [ ] R의 오른쪽 끝이 조금 빨갛게 변했는데, 파란색으로 고치기

**Comment by sanxiyn** [comment]
@lifthrasiir님 안입니다.

![rust-kr](https://cloud.githubusercontent.com/assets/45249/12741331/ac16a3b6-c9be-11e5-9b78-2c327e6210aa.png)

**Comment by kinoru** [comment]
기본적인 지적 사항들을 반영해서 사소한 수정을 했습니다.

- @sanxiyn 님의 지적([프로필 페이지](https://github.com/sanxiyn)에서 보듯 오리지널과 비교했을 때 획이 너무 가늘다는 문제가 있습니다)을 반영해서 굵기를 조절했습니다.
- 톱니 안쪽의 돌기와 ㄹ의 좌상단 획이 겹치는 것에 대해 지적이 있어서, 안쪽 돌기의 수를 네 개로 바꿨습니다.

![20160202_03](https://cloud.githubusercontent.com/assets/309724/12770437/ba80aee2-ca63-11e5-9cad-0d4dca2e68ba.png)

한시적으로 이대로 반영해도 무방할 것으로 생각합니다. 차후 "ㄹㅅㅌ" 등을 포함해 여러 가지 다양한 아이디어를 검토해볼 수 있겠죠.

SVG 소스 코드는 다음과 같습니다.

```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 540 540" height="540" width="540">
<path d="M420.125 57.5c.125-2.75-1-4.75-3.5-6.25-2.5-1.75-5-2-7.25-1L385.875 61l-5.75-3-4-25.5c-.5-2.75-2.125-4.5-4.75-5.5-2.75-1.25-5.125-1-7.25.5L343.25 42.75l-6.25-2-8.875-24c-1.125-2.5-3-4.125-5.75-4.75-2.875-.5-5.25.125-7 2l-17.5 19-6.5-.5-13.5-22c-1.375-2.25-3.5-3.25-6.5-3.25s-5.25 1-6.5 3.25l-13.5 22-6.5.5-17.5-19c-1.875-1.875-4.25-2.5-7-2-2.875.625-4.75 2.25-5.75 4.75l-9 24-6.25 2-20.75-15.25c-2.25-1.5-4.625-1.75-7.375-.5-2.625 1-4.125 2.75-4.625 5.5L162.5 58l-5.625 3-23.5-10.75c-2.375-1-4.75-.75-7.25 1-2.5 1.5-3.75 3.5-3.5 6.25l1 25.75-5 4.25-25.25-6c-2.5-.75-4.75 0-6.875 2.25-2.125 2-2.875 4.25-2.125 6.75l5.875 25.25-4.125 5-25.75-1c-2.75 0-4.75 1.125-6.25 3.5-1.75 2.5-2 4.875-1 7.25l10.75 23.5-3 5.75-25.5 4c-2.75.5-4.5 2-5.5 4.75-1.25 2.625-1 5 .5 7.25l15.25 20.75-2.125 6.25-23.875 9c-2.5 1-4 2.875-4.5 5.75-.75 3 0 5.25 2 7l18.75 17.5-.5 6.5-22 13.5c-2.25 1.25-3.375 3.5-3.375 6.5s1.125 5.125 3.375 6.5l22 13.5.5 6.5-18.75 17.5c-2 1.625-2.75 4-2 7 .5 2.75 2 4.75 4.5 5.75l23.875 9 2.125 6.25-15.25 20.75c-1.5 2.125-1.75 4.625-.5 7.25 1 2.75 2.75 4.375 5.5 4.75l25.5 4 3 5.75-10.75 23.5c-1 2.25-.75 4.75 1 7.25 1.5 2.5 3.5 3.625 6.25 3.5l25.75-1 4.125 5-5.875 25.25c-.75 2.5 0 4.75 2.125 6.75 2.125 2.125 4.375 2.875 6.875 2.25l25.25-6 5 4.25-1 25.75c-.25 2.625 1 4.75 3.5 6.25 2.5 1.625 4.875 2 7.25 1l23.5-10.75 5.625 3 4.125 25.5c.5 2.625 2 4.5 4.625 5.5 2.75 1.125 5.125 1 7.375-.5l20.75-15.25 6.25 2 9 24c1 2.5 2.875 4.125 5.75 4.75 3 .5 5.25-.25 7-2.25l17.5-18.75 6.5.5 13.5 22c1.25 2.25 3.5 3.5 6.5 3.5s5.125-1.25 6.5-3.5l13.5-22 6.5-.5 17.5 18.75c1.625 2 4 2.75 7 2.25 2.75-.625 4.625-2.25 5.75-4.75l8.875-24 6.25-2 20.875 15.25c2.125 1.5 4.5 1.625 7.25.5 2.625-1 4.25-2.875 4.75-5.5l4-25.5 5.75-3 23.5 10.75c2.25 1 4.75.625 7.25-1 2.5-1.5 3.625-3.625 3.5-6.25l-1-25.75 5-4.25 25.25 6c2.5.625 4.75-.125 6.75-2.25 2.125-2 2.875-4.25 2.25-6.75l-6-25.25 4.25-5 25.75 1c2.625.125 4.75-1 6.25-3.5 1.625-2.5 2-5 1-7.25l-10.75-23.5 3-5.75 25.5-4c2.625-.375 4.5-2 5.5-4.75 1.125-2.625 1-5.125-.5-7.25l-15.25-20.75 2-6.25 24-9c2.5-1 4-3 4.75-5.75.5-3-.25-5.375-2.25-7l-18.75-17.5.5-6.5 22-13.5c2.25-1.375 3.5-3.5 3.5-6.5s-1.25-5.25-3.5-6.5l-22-13.5-.5-6.5 18.75-17.5c2-1.75 2.75-4 2.25-7-.75-2.875-2.25-4.75-4.75-5.75l-24-9-2-6.25 15.25-20.75c1.5-2.25 1.625-4.625.5-7.25-1-2.75-2.875-4.25-5.5-4.75l-25.5-4-3-5.75 10.75-23.5c1-2.375.625-4.75-1-7.25-1.5-2.5-3.625-3.75-6.25-3.5l-25.75 1-4.25-5 6-25.25c.625-2.5-.125-4.75-2.25-6.75-2-2.25-4.25-3-6.75-2.25l-25.25 6-5-4.25 1-25.75M271.5 76.75c52.875 0 98.125 18.75 135.625 56.125 37.5 37.5 56.25 82.75 56.25 135.75 0 52.875-18.75 98.125-56.25 135.625S324.375 460.5 271.5 460.5c-53 0-98.375-18.75-135.75-56.25-37.5-37.5-56.25-82.75-56.125-135.625-.125-53 18.625-98.25 56.125-135.75C173.125 95.5 218.5 76.75 271.5 76.75z"/>
<path d="M235.625 457.25v33.875h70.75V457.25l-24-25.25c-6.5-6.75-13.125-6.875-20-.25l-26.75 25.5M260 455.375c3.125-3.25 7.125-4.875 11.625-4.875 4.625 0 8.5 1.625 11.75 4.875 3.25 3.125 4.875 7.125 4.875 11.625 0 4.625-1.625 8.5-4.875 11.75s-7.125 4.875-11.75 4.875c-4.5 0-8.5-1.625-11.625-4.875-3.25-3.25-4.875-7.125-4.875-11.75 0-4.5 1.625-8.5 4.875-11.625z"/>
<path d="M271.625 450.5c-4.5 0-8.5 1.625-11.625 4.875-3.25 3.125-4.875 7.125-4.875 11.625 0 4.625 1.625 8.5 4.875 11.75 3.125 3.25 7.125 4.875 11.625 4.875 4.625 0 8.5-1.625 11.75-4.875s4.875-7.125 4.875-11.75c0-4.5-1.625-8.5-4.875-11.625-3.25-3.25-7.125-4.875-11.75-4.875z" fill="#fff"/>
<path d="M460.125 304.25H494V233.5h-33.875l-25.25 24c-6.75 6.5-6.875 13.25-.25 20l25.5 26.75M458.25 280c-3.25-3.25-4.875-7.125-4.875-11.75 0-4.5 1.625-8.5 4.875-11.75 3.125-3.125 7.125-4.75 11.625-4.75 4.625 0 8.5 1.625 11.75 4.75 3.25 3.25 4.875 7.25 4.875 11.75 0 4.625-1.625 8.5-4.875 11.75s-7.125 4.875-11.75 4.875c-4.5 0-8.5-1.625-11.625-4.875z"/>
<path d="M453.375 268.25c0 4.625 1.625 8.5 4.875 11.75 3.125 3.25 7.125 4.875 11.625 4.875 4.625 0 8.5-1.625 11.75-4.875s4.875-7.125 4.875-11.75c0-4.5-1.625-8.5-4.875-11.75-3.25-3.125-7.125-4.75-11.75-4.75-4.5 0-8.5 1.625-11.625 4.75-3.25 3.25-4.875 7.25-4.875 11.75z" fill="#fff"/>
<path d="M307.125 80V46.125h-70.75V80l24 25.25c6.5 6.75 13.25 6.875 20 .25l26.75-25.5m-24.25 1.875c-3.25 3.25-7.125 4.875-11.75 4.875-4.5 0-8.5-1.625-11.75-4.875-3.125-3.125-4.75-7.125-4.75-11.625 0-4.625 1.625-8.5 4.75-11.75 3.25-3.25 7.25-4.875 11.75-4.875 4.625 0 8.5 1.625 11.75 4.875s4.875 7.125 4.875 11.75c0 4.5-1.625 8.5-4.875 11.625z"/>
<path d="M271.125 86.75c4.625 0 8.5-1.625 11.75-4.875 3.25-3.125 4.875-7.125 4.875-11.625 0-4.625-1.625-8.5-4.875-11.75s-7.125-4.875-11.75-4.875c-4.5 0-8.5 1.625-11.75 4.875-3.125 3.25-4.75 7.125-4.75 11.75 0 4.5 1.625 8.5 4.75 11.625 3.25 3.25 7.25 4.875 11.75 4.875z" fill="#fff"/>
<path d="M82.75 233H48.875v70.75H82.75l25.25-24c6.75-6.5 6.875-13.125.25-20L82.75 233m1.875 24.375C87.875 260.5 89.5 264.5 89.5 269c0 4.625-1.625 8.5-4.875 11.75C81.5 284 77.5 285.625 73 285.625c-4.625 0-8.5-1.625-11.75-4.875s-4.875-7.125-4.875-11.75c0-4.5 1.625-8.5 4.875-11.625 3.25-3.25 7.125-4.875 11.75-4.875 4.5 0 8.5 1.625 11.625 4.875z"/>
<path d="M89.5 269c0-4.5-1.625-8.5-4.875-11.625C81.5 254.125 77.5 252.5 73 252.5c-4.625 0-8.5 1.625-11.75 4.875C58 260.5 56.375 264.5 56.375 269c0 4.625 1.625 8.5 4.875 11.75s7.125 4.875 11.75 4.875c4.5 0 8.5-1.625 11.625-4.875 3.25-3.25 4.875-7.125 4.875-11.75z" fill="#fff"/>
<path d="M395.5 185.75c2.625-7.875 2-14.5-2-20.125-3.75-5.5-9.875-8.375-18.125-8.625h-294.5L59.5 215.75H322l-8.5 23.5h-125l-41 112.375c-2.625 7.75-2 14.5 1.875 20 4 5.5 10 8.375 18.125 8.625h294.625L483.5 321.5H221l8.625-23.5H354.5l41-112.25z"/>
</svg>
```

**Comment by lifthrasiir** [comment]
@kinoru 이 안으로 갱신했습니다.
